name:  mqtt_mobile_client
description: A professional-grade MQTT client application built with Flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^10.0.0
  web_socket_channel: ^2.4.0
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8
  file_picker: ^6.1.1  # For certificate file picking
  x509: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


